config:
  - dmhy: 极影字幕社 YU-NO GB_CN
    fileNamePattern: YU-NO
    bangumiName: YU-NO
  - dmhy: 满月之战 简日双语
    fileNamePattern: GRANBELM
    bangumiName: 满月之战
  - dmhy: LoliHouse 为了女儿，我说不定连魔王都能干掉。
    fileNamePattern: Uchinoko
    bangumiName: 为了女儿，我说不定连魔王都能干掉
  - dmhy: MMSUB 异世界超能魔术师
    fileNamePattern: Isekai Cheat Magician
    bangumiName: 异世界超能魔术师
  - dmhy: 喵萌奶茶屋 你遭难了吗 简体
    fileNamePattern: Sounan desu ka
    bangumiName: 你遭难了吗
  - dmhy: 幻樱字幕组 魔术学姐 GB_MP4
    fileNamePattern: Tejina Senpai
    bangumiName: 魔术学姐
  - dmhy: 喵萌奶茶屋 平凡职业成就世界最强 简体
    fileNamePattern: Arifureta Shokugyou de Sekai Saikyou
    bangumiName: 平凡职业成就世界最强
  - dmhy: 喵萌奶茶屋 女高中生的无用日常 简体
    fileNamePattern: Joshikousei no Mudazukai
    bangumiName: 女高中生的无用日常
  - dmhy: 轻之国度 肌肉少女：哑铃，能举多少公斤？
    fileNamePattern: Dumbbell Nan Kilo Moteru
    bangumiName: 肌肉少女：哑铃，能举多少公斤？
  - dmhy: 漫猫 魔王大人
    fileNamePattern: Maou-sama, Retry
    bangumiName: 重来吧!魔王大人
  - dmhy: BYYM 普通攻擊 HEVC
    fileNamePattern: Okaasan
    bangumiName: 你妈平砍连击带顺劈
  - dmhy: 喵萌奶茶屋 街角魔族 1080p 简体
    fileNamePattern: Machikado Mazoku
    bangumiName: 街角魔族
  - dmhy: MMSUB 某科学的一方通行
    fileNamePattern: Toaru Kagaku no Accelerator
    bangumiName: 某科学的一方通行
  - dmhy: BYYM 在地下城尋求邂逅是否搞錯了什麼 HEVC
    fileNamePattern: DanMachi S2
    bangumiName: 地错
  - dmhy: 星空字幕组 炎炎消防队 MP4
    fileNamePattern: Fire_Force
    bangumiName: 炎炎消防队
  - dmhy: 千夏字幕组 擅长捉弄人的高木同学2 简体
    fileNamePattern: Karakai Jouzu no Takagi-san 2
    bangumiName: 擅长捉弄人的高木同学2
  - dmhy: 动漫国 彼方的阿斯特拉 简体 1080P
    fileNamePattern: Kanata_no_Astra
    bangumiName: 彼方的阿斯特拉
  - dmhy: BYYM BEM
    fileNamePattern: "[BEM]"
    bangumiName: BEM
